"""update_model_registry

Revision ID: d62cca91d1b8
Revises: 3d7e22918edc
Create Date: 2026-06-05 21:17:20.942586+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd62cca91d1b8'
down_revision: Union[str, None] = '3d7e22918edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('intraday_ticks', 'bid_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('intraday_ticks', 'ask_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('intraday_ticks', 'bid_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('intraday_ticks', 'ask_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('intraday_ticks', 'volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               nullable=True)
    op.add_column('model_registry', sa.Column('artifact_path', sa.String(), nullable=False))
    op.add_column('model_registry', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('model_registry', sa.Column('active', sa.Boolean(), nullable=False))
    op.drop_column('model_registry', 'metrics_json')
    op.drop_column('model_registry', 'schema_version')
    op.drop_column('model_registry', 'trained_at')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_registry', sa.Column('trained_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('model_registry', sa.Column('schema_version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('model_registry', sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('model_registry', 'active')
    op.drop_column('model_registry', 'created_at')
    op.drop_column('model_registry', 'artifact_path')
    op.alter_column('intraday_ticks', 'volume',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('intraday_ticks', 'ask_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('intraday_ticks', 'bid_qty',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('intraday_ticks', 'ask_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('intraday_ticks', 'bid_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
