"""initial_schema

Revision ID: 3d7e22918edc
Revises:
Create Date: 2026-06-01 20:50:27.921110+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3d7e22918edc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_ohlcv",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_daily_ohlcv_symbol"), "daily_ohlcv", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_daily_ohlcv_trade_date"), "daily_ohlcv", ["trade_date"], unique=False
    )
    op.create_table(
        "intraday_ticks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ltp", sa.Float(), nullable=False),
        sa.Column("bid_price", sa.Float(), nullable=False),
        sa.Column("ask_price", sa.Float(), nullable=False),
        sa.Column("bid_qty", sa.Float(), nullable=False),
        sa.Column("ask_qty", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("cold_storage_uploaded", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_intraday_ticks_symbol"), "intraday_ticks", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_intraday_ticks_timestamp"),
        "intraday_ticks",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "model_registry",
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "metrics_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("schema_version", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("model_name", "version"),
    )
    op.create_table(
        "portfolio_holdings",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("avg_buy_price", sa.Float(), nullable=False),
        sa.Column("buy_date", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_table(
        "trading_signals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("signal", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("target_price", sa.Float(), nullable=False),
        sa.Column("prediction_source", sa.String(), nullable=False),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trading_signals_symbol"), "trading_signals", ["symbol"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trading_signals_symbol"), table_name="trading_signals")
    op.drop_table("trading_signals")
    op.drop_table("portfolio_holdings")
    op.drop_table("model_registry")
    op.drop_index(op.f("ix_intraday_ticks_timestamp"), table_name="intraday_ticks")
    op.drop_index(op.f("ix_intraday_ticks_symbol"), table_name="intraday_ticks")
    op.drop_table("intraday_ticks")
    op.drop_index(op.f("ix_daily_ohlcv_trade_date"), table_name="daily_ohlcv")
    op.drop_index(op.f("ix_daily_ohlcv_symbol"), table_name="daily_ohlcv")
    op.drop_table("daily_ohlcv")
    # ### end Alembic commands ###
